# Generated by Django 3.0.2 on 2020-01-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('SongName', models.CharField(max_length=100)),
                ('Lyric', models.TextField()),
                ('Lyrics', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicType', models.CharField(max_length=100)),
                ('SongName', models.CharField(max_length=100)),
                ('Music_User', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('User', models.ManyToManyField(to='Harmonyapp.Music')),
                ('Users', models.ManyToManyField(to='Harmonyapp.Lyrics')),
            ],
        ),
        migrations.AddField(
            model_name='lyrics',
            name='music_lyrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Harmonyapp.Music'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Songs', models.CharField(max_length=100)),
                ('Artist_Music', models.ManyToManyField(to='Harmonyapp.Music')),
            ],
        ),
    ]
